# Scrapping Data Using APIs

## Yahoo API

Retrieved 50 tech companies worth of historical data. Measured which company is the most immune to covid outbreaks.

In [1]:
import yfinance as yahoo
import pandas as pd
from googleapiclient.discovery import build
%matplotlib inline
import numpy as np
import collections

In [2]:
techs = ['AAPL','MSFT','NVDA','TSM','ASML',
        'AVGO','CSCO','ORCL','CRM','ADBE',
        'ACN','INTC','AMD','QCOM','TXN',
        'INTU','SAP','SONY','AMAT','NOW',
        'IBM','INFY','SHOP','MU','ADI',
        'SQ','TEAM','LRCX','FISV','SNOW',
        'UBER','FIS','PANW','WDAY','MRVL',
        'FTNT','KLAC','SNPS','CRWD','VMW',
        'NXPI','CTSH','CDNS','ADSK','APH',
        'COIN','DDOG','WIT','TEL','ANET']

In [3]:
multdata = yahoo.download(techs, start='2020-01-01',end='2022-01-01')

[*********************100%***********************]  50 of 50 completed

In [4]:
multiple_techs = yahoo.Tickers(techs)
multiple_techs

yfinance.Tickers object <AAPL,MSFT,NVDA,TSM,ASML,AVGO,CSCO,ORCL,CRM,ADBE,ACN,INTC,AMD,QCOM,TXN,INTU,SAP,SONY,AMAT,NOW,IBM,INFY,SHOP,MU,ADI,SQ,TEAM,LRCX,FISV,SNOW,UBER,FIS,PANW,WDAY,MRVL,FTNT,KLAC,SNPS,CRWD,VMW,NXPI,CTSH,CDNS,ADSK,APH,COIN,DDOG,WIT,TEL,ANET>

In [5]:
multiple_techs.tickers

{'AAPL': yfinance.Ticker object <AAPL>,
 'MSFT': yfinance.Ticker object <MSFT>,
 'NVDA': yfinance.Ticker object <NVDA>,
 'TSM': yfinance.Ticker object <TSM>,
 'ASML': yfinance.Ticker object <ASML>,
 'AVGO': yfinance.Ticker object <AVGO>,
 'CSCO': yfinance.Ticker object <CSCO>,
 'ORCL': yfinance.Ticker object <ORCL>,
 'CRM': yfinance.Ticker object <CRM>,
 'ADBE': yfinance.Ticker object <ADBE>,
 'ACN': yfinance.Ticker object <ACN>,
 'INTC': yfinance.Ticker object <INTC>,
 'AMD': yfinance.Ticker object <AMD>,
 'QCOM': yfinance.Ticker object <QCOM>,
 'TXN': yfinance.Ticker object <TXN>,
 'INTU': yfinance.Ticker object <INTU>,
 'SAP': yfinance.Ticker object <SAP>,
 'SONY': yfinance.Ticker object <SONY>,
 'AMAT': yfinance.Ticker object <AMAT>,
 'NOW': yfinance.Ticker object <NOW>,
 'IBM': yfinance.Ticker object <IBM>,
 'INFY': yfinance.Ticker object <INFY>,
 'SHOP': yfinance.Ticker object <SHOP>,
 'MU': yfinance.Ticker object <MU>,
 'ADI': yfinance.Ticker object <ADI>,
 'SQ': yfinance.Ticker object <SQ>,
 'TEAM': yfinance.Ticker object <TEAM>,
 'LRCX': yfinance.Ticker object <LRCX>,
 'FISV': yfinance.Ticker object <FISV>,
 'SNOW': yfinance.Ticker object <SNOW>,
 'UBER': yfinance.Ticker object <UBER>,
 'FIS': yfinance.Ticker object <FIS>,
 'PANW': yfinance.Ticker object <PANW>,
 'WDAY': yfinance.Ticker object <WDAY>,
 'MRVL': yfinance.Ticker object <MRVL>,
 'FTNT': yfinance.Ticker object <FTNT>,
 'KLAC': yfinance.Ticker object <KLAC>,
 'SNPS': yfinance.Ticker object <SNPS>,
 'CRWD': yfinance.Ticker object <CRWD>,
 'VMW': yfinance.Ticker object <VMW>,
 'NXPI': yfinance.Ticker object <NXPI>,
 'CTSH': yfinance.Ticker object <CTSH>,
 'CDNS': yfinance.Ticker object <CDNS>,
 'ADSK': yfinance.Ticker object <ADSK>,
 'APH': yfinance.Ticker object <APH>,
 'COIN': yfinance.Ticker object <COIN>,
 'DDOG': yfinance.Ticker object <DDOG>,
 'WIT': yfinance.Ticker object <WIT>,
 'TEL': yfinance.Ticker object <TEL>,
 'ANET': yfinance.Ticker object <ANET>}

In [6]:
techs_history = multiple_techs.history(start='2020-01-01',end='2022-01-01')
techs_history

[*********************100%***********************]  50 of 50 completed

                 Close                                                  \
                  AAPL         ACN        ADBE         ADI        ADSK
Date
2020-01-02   73.785919  203.171112  334.429993  115.498466  187.830002
2020-01-03   73.068565  202.832733  331.809998  113.465294  184.949997
2020-01-06   73.650803  201.508255  333.709991  112.132179  187.119995
2020-01-07   73.304405  197.157700  333.390015  114.683289  187.500000
2020-01-08   74.483612  197.544418  337.869995  115.719048  189.949997
...                ...         ...         ...         ...         ...
2021-12-27  179.836319  413.026154  577.679993  174.617828  284.299988
2021-12-28  178.799164  412.966461  569.359985  173.533127  282.769989
2021-12-29  178.888916  413.115692  569.289978  174.667587  282.570007
2021-12-30  177.712143  411.534454  570.530029  173.931168  281.709991
2021-12-31  177.083878  412.250458  567.059998  174.916367  281.190002

                                                                       ...  \
                  AMAT         AMD        ANET        APH        ASML  ...
Date                                                                   ...
2020-01-02   60.829201   49.099998   51.180000  53.437366  296.300354  ...
2020-01-03   59.861019   48.599998   50.212502  52.879650  291.525604  ...
2020-01-06   58.570114   48.389999   50.715000  52.605690  289.206696  ...
2020-01-07   60.261982   48.250000   51.212502  52.889439  292.347504  ...
2020-01-08   60.222866   47.830002   51.744999  53.016636  295.380646  ...
...                ...         ...         ...        ...         ...  ...
2021-12-27  162.427139  154.360001  146.839996  86.703445  805.476624  ...
2021-12-28  159.352692  153.149994  144.889999  86.892952  798.865540  ...
2021-12-29  160.690277  148.259995  145.710007  87.710815  796.095947  ...
2021-12-30  157.695663  145.149994  143.149994  86.793205  794.348877  ...
2021-12-31  157.076797  143.899994  143.750000  87.232063  790.298828  ...

             Volume                                                           \
               SONY        SQ     TEAM      TEL       TSM      TXN      UBER
Date
2020-01-02   856500   5264700  2062500  1866500   8432600  4614000  20578900
2020-01-03   518600   5087100  1223600  1439800  10546400  4057200  18822700
2020-01-06   755500   5905200  3583800  1150100   8897200  4345400  21204700
2020-01-07  1316200  10368200  1560400  2103400   7444300  7184100  30119600
2020-01-08  1640200  11899200  1570400  2001000   5381500  3546900  43944400
...             ...       ...      ...      ...       ...      ...       ...
2021-12-27   548200   5468500   758200   829700   6309900  3405600  28285000
2021-12-28   415700   6570500   648900   687500   6321000  2806900  21481000
2021-12-29   259100   7021900   627600  1156400   5847700  2754900  15908600
2021-12-30   232200   6656700   834600   675400   4187800  2109200  13516300
2021-12-31   275000   6448500   556300   592200   3888200  2813900  13746900


                VMW     WDAY      WIT
Date
2020-01-02  1095700  1503000   524800
2020-01-03  1058200  1276300   417900
2020-01-06   779800  1623300   727200
2020-01-07  1259400  2404100  1034000
2020-01-08  1598400  2819900   908700
...             ...      ...      ...
2021-12-27   974000  1055500   783400
2021-12-28  1459600   859300   705600
2021-12-29   988200   757400   586600
2021-12-30   977600  1535400   953800
2021-12-31  1080500   754300   600800

[505 rows x 350 columns]

In [7]:
techs_history.describe(include = 'all') # To see all of the stats

            Close                                                              \
             AAPL         ACN        ADBE         ADI        ADSK        AMAT
count  505.000000  505.000000  505.000000  505.000000  505.000000  505.000000
mean   117.169495  256.997874  488.149248  138.153096  256.723584   95.805286
std     29.604922   61.023616  101.565881   27.399137   47.452352   37.384351
min     55.250996  139.455246  285.000000   79.290810  136.000000   37.269836
25%     90.502144  210.011093  432.420013  113.654236  231.009995   60.081924
50%    122.838203  248.427734  481.260010  142.928162  269.000000   88.351494
75%    140.518600  301.400909  569.289978  162.390381  292.170013  133.946030
max    179.836319  413.115692  688.369995  187.166229  342.269989  162.427139

                                                       ...        Volume  \
              AMD        ANET         APH        ASML  ...          SONY
count  505.000000  505.000000  505.000000  505.000000  ...  5.050000e+02
mean    83.347624   74.314876   61.026350  517.817937  ...  9.813855e+05
std     27.121054   23.304628   12.601389  195.760567  ...  5.252914e+05
min     38.709999   39.259998   33.538536  192.742508  ...  2.322000e+05
25%     56.389999   54.862499   51.316395  355.309448  ...  6.064000e+05
50%     82.239998   70.925003   63.704491  483.642914  ...  8.568000e+05
75%     93.769997   89.782501   68.352104  690.121643  ...  1.212000e+06
max    161.910004  146.839996   87.710815  880.515686  ...  3.626500e+06

                                                                             \
                 SQ          TEAM           TEL           TSM           TXN
count  5.050000e+02  5.050000e+02  5.050000e+02  5.050000e+02  5.050000e+02
mean   1.057575e+07  1.553706e+06  1.728076e+06  9.510463e+06  4.703257e+06
std    5.628761e+06  8.504478e+05  7.469417e+05  4.520092e+06  2.127235e+06
min    3.428700e+06  4.494000e+05  5.906000e+05  3.172100e+06  1.044400e+06
25%    6.711500e+06  9.462000e+05  1.254000e+06  6.523200e+06  3.276300e+06
50%    9.193600e+06  1.419200e+06  1.580200e+06  8.424900e+06  4.270100e+06
75%    1.254400e+07  1.970800e+06  2.018700e+06  1.102660e+07  5.426500e+06
max    4.573060e+07  8.033700e+06  6.009000e+06  4.122680e+07  1.641390e+07


               UBER           VMW          WDAY           WIT
count  5.050000e+02  5.050000e+02  5.050000e+02  5.050000e+02
mean   2.552029e+07  1.468124e+06  1.933735e+06  1.575790e+06
std    1.445535e+07  9.988184e+05  1.221368e+06  8.225771e+05
min    6.316800e+06  3.461000e+05  5.632000e+05  2.990000e+05
25%    1.634680e+07  8.714000e+05  1.225500e+06  9.809000e+05
50%    2.130650e+07  1.162600e+06  1.644900e+06  1.434500e+06
75%    2.982070e+07  1.685700e+06  2.206000e+06  2.010200e+06
max    1.123258e+08  1.109900e+07  1.227460e+07  7.381100e+06

[8 rows x 350 columns]

In [8]:
techs_history.shape

(505, 350)

In [9]:
techs_history.dtypes

Close   AAPL    float64
        ACN     float64
        ADBE    float64
        ADI     float64
        ADSK    float64
                 ...
Volume  TXN       int64
        UBER      int64
        VMW       int64
        WDAY      int64
        WIT       int64
Length: 350, dtype: object

In [31]:

close = techs_history['Close']
close

,AAPL,ACN,ADBE,ADI,ADSK,AMAT,AMD,ANET,APH,ASML,...,SONY,SQ,TEAM,TEL,TSM,TXN,UBER,VMW,WDAY,WIT
Date,,,,,,,,,,,,,,,,,,,,,
2020-01-02,73.785919,203.171112,334.429993,115.498466,187.830002,60.829201,49.099998,51.180000,53.437366,296.300354,...,69.059998,63.830002,122.879997,92.509087,57.290359,121.339493,30.990000,127.666656,167.460007,3.700613
2020-01-03,73.068565,202.832733,331.809998,113.465294,184.949997,59.861019,48.599998,50.212502,52.879650,291.525604,...,68.080002,63.000000,123.040001,91.416344,55.401035,119.728745,31.370001,126.337822,168.440002,3.730139
2020-01-06,73.650803,201.508255,333.709991,112.132179,187.119995,58.570114,48.389999,50.715000,52.605690,289.206696,...,69.110001,62.570000,127.690002,90.783707,54.761715,118.895279,31.580000,126.370628,169.490005,3.789192
2020-01-07,73.304405,197.157700,333.390015,114.683289,187.500000,60.261982,48.250000,51.212502,52.889439,292.347504,...,70.199997,64.589996,128.149994,92.662445,55.649124,121.189644,32.810001,123.319229,172.949997,3.789192
2020-01-08,74.483612,197.544418,337.869995,115.719048,189.949997,60.222866,47.830002,51.744999,53.016636,295.380646,...,70.459999,67.599998,130.059998,93.620995,56.059437,121.517418,33.930000,124.311760,178.710007,3.799033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-27,179.836319,413.026154,577.679993,174.617828,284.299988,162.427139,154.360001,146.839996,86.703445,805.476624,...,127.209999,168.479996,394.429993,161.503616,122.111076,189.290878,42.959999,116.279999,279.350006,9.543224
2021-12-28,178.799164,412.966461,569.359985,173.533127,282.769989,159.352692,153.149994,144.889999,86.892952,798.865540,...,127.480003,163.669998,388.609985,161.305206,121.474152,188.560730,42.540001,117.480003,275.799988,9.533324
2021-12-29,178.888916,413.115692,569.289978,174.667587,282.570007,160.690277,148.259995,145.710007,87.710815,796.095947,...,126.690002,161.850006,382.779999,161.146469,120.827278,188.274582,42.459999,117.879997,275.750000,9.582823
2021-12-30,177.712143,411.534454,570.530029,173.931168,281.709991,157.695663,145.149994,143.149994,86.793205,794.348877,...,125.919998,165.339996,385.359985,159.321014,119.842026,186.893173,42.660000,117.260002,276.500000,9.662020
2021-12-31,177.083878,412.250458,567.059998,174.916367,281.190002,157.076797,143.899994,143.750000,87.232063,790.298828,...,126.400002,161.509995,381.290009,160.065079,119.732552,185.965668,41.930000,115.879997,273.179993,9.662020

In [33]:
closing_old = close.iloc[0]
closing_new = close.iloc[504]

In [34]:
percent_change = ((closing_new - closing_old)/closing_new) * 100
percent_change

AAPL    58.332785
ACN     50.716583
ADBE    41.023879
ADI     33.969320
ADSK    33.201750
AMAT    61.274229
AMD     65.879082
ANET    64.396522
APH     38.741141
ASML    62.507808
AVGO    55.002738
CDNS    61.663536
COIN          NaN
CRM     34.289536
CRWD    75.853481
CSCO    27.707045
CTSH    32.006666
DDOG    79.394756
FIS    -25.389018
FISV   -11.301663
FTNT    69.482470
IBM     12.374232
INFY    61.084586
INTC   -12.356356
INTU    59.157198
KLAC    58.783419
LRCX    59.617888
MRVL    69.023325
MSFT    53.135372
MU      40.683020
NOW     55.132413
NVDA    79.658478
NXPI    44.912839
ORCL    40.129890
PANW    57.717868
QCOM    53.567652
SAP      5.299893
SHOP    70.392555
SNOW          NaN
SNPS    61.229309
SONY    45.363927
SQ      60.479225
TEAM    67.772563
TEL     42.205328
TSM     52.151392
TXN     34.751670
UBER    26.091105
VMW    -10.171436
WDAY    38.699754
WIT     61.699385
dtype: float64

In [35]:
# Seems to think everybody had a great or okay year, but INTC (Intel Corporation), VMW (VMware, intc.), FISV (Fiser, inc). 
#There are missing values for COIN (Coinbase Global) and SNOW (Snowflake Inc)
best_percent_change = percent_change.sort_values(ascending = False)
best_percent_change

NVDA    79.658478
DDOG    79.394756
CRWD    75.853481
SHOP    70.392555
FTNT    69.482470
MRVL    69.023325
TEAM    67.772563
AMD     65.879082
ANET    64.396522
ASML    62.507808
WIT     61.699385
CDNS    61.663536
AMAT    61.274229
SNPS    61.229309
INFY    61.084586
SQ      60.479225
LRCX    59.617888
INTU    59.157198
KLAC    58.783419
AAPL    58.332785
PANW    57.717868
NOW     55.132413
AVGO    55.002738
QCOM    53.567652
MSFT    53.135372
TSM     52.151392
ACN     50.716583
SONY    45.363927
NXPI    44.912839
TEL     42.205328
ADBE    41.023879
MU      40.683020
ORCL    40.129890
APH     38.741141
WDAY    38.699754
TXN     34.751670
CRM     34.289536
ADI     33.969320
ADSK    33.201750
CTSH    32.006666
CSCO    27.707045
UBER    26.091105
IBM     12.374232
SAP      5.299893
VMW    -10.171436
FISV   -11.301663
INTC   -12.356356
FIS    -25.389018
COIN          NaN
SNOW          NaN
dtype: float64

 YouTube API

Find the Youtuber with the most calculus videos.

In [15]:
!pip install google-api-python-client

Requirement already satisfied: google-api-python-client in c:\users\apple\anaconda3\lib\site-packages (2.42.0)
Requirement already satisfied: google-auth<3.0.0dev,>=1.16.0 in c:\users\apple\anaconda3\lib\site-packages (from google-api-python-client) (2.6.2)
Requirement already satisfied: uritemplate<5,>=3.0.1 in c:\users\apple\anaconda3\lib\site-packages (from google-api-python-client) (4.1.1)
Requirement already satisfied: google-auth-httplib2>=0.1.0 in c:\users\apple\anaconda3\lib\site-packages (from google-api-python-client) (0.1.0)
Requirement already satisfied: google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5 in c:\users\apple\anaconda3\lib\site-packages (from google-api-python-client) (2.7.1)
Requirement already satisfied: httplib2<1dev,>=0.15.0 in c:\users\apple\anaconda3\lib\site-packages (from google-api-python-client) (0.20.4)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in c:\users\apple\anaconda3\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.26.0)
Requirement already satisfied: protobuf>=3.12.0 in c:\users\apple\anaconda3\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (3.19.4)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.52.0 in c:\users\apple\anaconda3\lib\site-packages (from google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.56.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\apple\anaconda3\lib\site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (5.0.0)
Requirement already satisfied: six>=1.9.0 in c:\users\apple\appdata\roaming\python\python39\site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (1.15.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\apple\anaconda3\lib\site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\apple\anaconda3\lib\site-packages (from google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (4.8)
Requirement already satisfied: pyparsing!=3.0.0,!=3.0.1,!=3.0.2,!=3.0.3,<4,>=2.4.2 in c:\users\apple\anaconda3\lib\site-packages (from httplib2<1dev,>=0.15.0->google-api-python-client) (3.0.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\apple\anaconda3\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3.0.0dev,>=1.16.0->google-api-python-client) (0.4.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\apple\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\apple\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (3.2)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\apple\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (1.26.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\apple\anaconda3\lib\site-packages (from requests<3.0.0dev,>=2.18.0->google-api-core!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0,<3.0.0dev,>=1.31.5->google-api-python-client) (2021.10.8)

Built a pandas data set of views, likes, number of comments, titles, channel titles, channel ID of videos about learning calculus.

In [16]:
apikey='AIzaSyAQ6ry5ycEL4jvNkn5cOdfjyR-R2n0mcwM'
Ytube=build('youtube','v3',developerKey=apikey)
type(Ytube)

googleapiclient.discovery.Resource

In [17]:
calc_request = Ytube.search().list(part = "snippet", maxResults = 25, q = 'calculus', type = 'videos') 
calc_results = calc_request.execute()

In [18]:
calc_results

{'kind': 'youtube#searchListResponse',
 'etag': 'WNj5gNe0k4X5SoKIk5_ON7dcNHc',
 'nextPageToken': 'CBkQAA',
 'regionCode': 'US',
 'pageInfo': {'totalResults': 1000000, 'resultsPerPage': 25},
 'items': [{'kind': 'youtube#searchResult',
   'etag': 'S8kQHVvW9NJ58dx80cjinVM3DBs',
   'id': {'kind': 'youtube#video', 'videoId': 'WsQQvHm4lSw'},
   'snippet': {'publishedAt': '2018-09-10T15:50:55Z',
    'channelId': 'UCEWpbFLzoYGPfuWUMFPSaoA',
    'title': 'Understand Calculus in 35 Minutes',
    'description': 'This video makes an attempt to teach the fundamentals of calculus 1 such as limits, derivatives, and integration. It explains how to ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/WsQQvHm4lSw/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/WsQQvHm4lSw/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/WsQQvHm4lSw/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'The Organic Chemistry Tutor',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-09-10T15:50:55Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'Z4fRJDr1NugW2UtEbxE6EeLi7So',
   'id': {'kind': 'youtube#video', 'videoId': 'HfACrKJ_Y2w'},
   'snippet': {'publishedAt': '2020-08-25T15:30:08Z',
    'channelId': 'UC8butISFwT-Wl7EV0hUK0BQ',
    'title': 'Calculus 1 - Full College Course',
    'description': 'Learn Calculus 1 in this full college course. This course was created by Dr. Linda Green, a lecturer at the University of North ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/HfACrKJ_Y2w/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/HfACrKJ_Y2w/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/HfACrKJ_Y2w/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'freeCodeCamp.org',
    'liveBroadcastContent': 'none',
    'publishTime': '2020-08-25T15:30:08Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'jw9JK_1OKhD-am1DCkIVfM96imA',
   'id': {'kind': 'youtube#video', 'videoId': 'WUvTyaaNkzM'},
   'snippet': {'publishedAt': '2017-04-28T15:58:48Z',
    'channelId': 'UCYO_jab_esuFRV4b17AJtAw',
    'title': 'The essence of calculus',
    'description': 'What might it feel like to invent calculus? Help fund future projects: https://www.patreon.com/3blue1brown An equally valuable ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/WUvTyaaNkzM/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/WUvTyaaNkzM/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/WUvTyaaNkzM/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': '3Blue1Brown',
    'liveBroadcastContent': 'none',
    'publishTime': '2017-04-28T15:58:48Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'XwVjiCwnVfdZznXMWiiDWCIIl08',
   'id': {'kind': 'youtube#video', 'videoId': 'WjJ-kpgps1c'},
   'snippet': {'publishedAt': '2017-05-19T16:12:43Z',
    'channelId': 'UCglNXzBo6bmKc9otKf-OuGQ',
    'title': 'Understand Calculus in 10 Minutes',
    'description': 'TabletClass Math http://www.tabletclass.com learn the basics of calculus quickly. This video is designed to introduce calculus ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/WjJ-kpgps1c/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/WjJ-kpgps1c/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/WjJ-kpgps1c/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'TabletClass Math',
    'liveBroadcastContent': 'none',
    'publishTime': '2017-05-19T16:12:43Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'Gyk6W3E6Suxiy4f0An9kOWBIU9c',
   'id': {'kind': 'youtube#video', 'videoId': 'UukVP7Mg3TU'},
   'snippet': {'publishedAt': '2015-11-19T22:00:29Z',
    'channelId': 'UCcBOg_7QmpJFlIVMYDyUhaw',
    'title': 'Calculus - Introduction to Calculus',
    'description': 'This video will give you a brief introduction to calculus. It does this by explaining that calculus is the mathematics of change.',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/UukVP7Mg3TU/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/UukVP7Mg3TU/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/UukVP7Mg3TU/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'MySecretMathTutor',
    'liveBroadcastContent': 'none',
    'publishTime': '2015-11-19T22:00:29Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '27q8qKp-Jf6Hmgz42sWx942hV8g',
   'id': {'kind': 'youtube#video', 'videoId': '54_XRjHhZzI'},
   'snippet': {'publishedAt': '2012-08-22T21:22:51Z',
    'channelId': 'UCoHhuummRZaIVX7bD4t2czg',
    'title': 'Calculus 1 Lecture 1.1:  An Introduction to Limits',
    'description': 'https://www.patreon.com/ProfessorLeonard Calculus 1 Lecture 1.1: An Introduction to Limits.',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/54_XRjHhZzI/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/54_XRjHhZzI/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/54_XRjHhZzI/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Professor Leonard',
    'liveBroadcastContent': 'none',
    'publishTime': '2012-08-22T21:22:51Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'DItMECVubTMEovE-_tLNgsdzrS0',
   'id': {'kind': 'youtube#playlist', 'playlistId': 'PLF797E961509B4EB5'},
   'snippet': {'publishedAt': '2012-05-23T17:21:47Z',
    'channelId': 'UCoHhuummRZaIVX7bD4t2czg',
    'title': 'Calculus 1 (Full Length Videos)',
    'description': 'Topics: Review of Algebra/Trigonometric Concepts, Finding Limits, Derivatives and Derivative Techniques, Integrals and Integral ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/fYyARMqiaag/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/fYyARMqiaag/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/fYyARMqiaag/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Professor Leonard',
    'liveBroadcastContent': 'none',
    'publishTime': '2012-05-23T17:21:47Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'TK-iXsjVAcTQzVERWgW_bMCKhnA',
   'id': {'kind': 'youtube#video', 'videoId': 'NjvwWiCYLl4'},
   'snippet': {'publishedAt': '2020-04-08T16:41:07Z',
    'channelId': 'UC6A_Wd8sUo5hRhn14Oxa7-A',
    'title': 'How to Make it Through Calculus (Neil deGrasse Tyson)',
    'description': 'Neil deGrasse Tyson talks about his personal struggles taking calculus and what it took for him to ultimately become successful at ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/NjvwWiCYLl4/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/NjvwWiCYLl4/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/NjvwWiCYLl4/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Jonathan Arrington',
    'liveBroadcastContent': 'none',
    'publishTime': '2020-04-08T16:41:07Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '4sS8GIA9tQpq826k98oOk-m9ox4',
   'id': {'kind': 'youtube#video', 'videoId': 'w3GV9pumczQ'},
   'snippet': {'publishedAt': '2016-09-29T17:17:28Z',
    'channelId': 'UCW6TXMZ5Pq6yL6_k5NZ2e0Q',
    'title': 'What is Calculus?  (Mathematics)',
    'description': 'What is Calculus? In this video, we give you a quick overview of calculus and introduce the limit, derivative and integral. We begin ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/w3GV9pumczQ/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/w3GV9pumczQ/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/w3GV9pumczQ/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Socratica',
    'liveBroadcastContent': 'none',
    'publishTime': '2016-09-29T17:17:28Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'ifAeeR8UPHU8iv5YhqLfeO2GUSU',
   'id': {'kind': 'youtube#video', 'videoId': 'CvOQLWebWQI'},
   'snippet': {'publishedAt': '2021-12-03T18:10:11Z',
    'channelId': 'UCglNXzBo6bmKc9otKf-OuGQ',
    'title': 'Your First Basic CALCULUS Problem Let’s Do It Together….',
    'description': 'TabletClass Math: https://tcmathacademy.com/ Learn how to do calculus with this basic problem. For more math help to include ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/CvOQLWebWQI/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/CvOQLWebWQI/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/CvOQLWebWQI/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'TabletClass Math',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-12-03T18:10:11Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '4idsEjxI38wEoUQP_QU5KRNYjSI',
   'id': {'kind': 'youtube#video', 'videoId': 'YNstP0ESndU'},
   'snippet': {'publishedAt': '2021-01-01T22:09:32Z',
    'channelId': 'UCEWpbFLzoYGPfuWUMFPSaoA',
    'title': 'Calculus 1 - Introduction to Limits',
    'description': 'This calculus 1 video tutorial provides an introduction to limits. It explains how to evaluate limits by direct substitution, by factoring, ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/YNstP0ESndU/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/YNstP0ESndU/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/YNstP0ESndU/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'The Organic Chemistry Tutor',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-01-01T22:09:32Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '8Ewk-q-CFtb2NVbcXpNNiXK5OR4',
   'id': {'kind': 'youtube#playlist',
    'playlistId': 'PLZHQObOWTQDMsr9K-rj53DwVRMYO3t5Yr'},
   'snippet': {'publishedAt': '2017-04-28T05:50:12Z',
    'channelId': 'UCYO_jab_esuFRV4b17AJtAw',
    'title': 'Essence of calculus',
    'description': 'The goal here is to make calculus feel like something that you yourself could have discovered.',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/WUvTyaaNkzM/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/WUvTyaaNkzM/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/WUvTyaaNkzM/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': '3Blue1Brown',
    'liveBroadcastContent': 'none',
    'publishTime': '2017-04-28T05:50:12Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'Y2e2JkhYGLhj8gENIocM4BYbzp0',
   'id': {'kind': 'youtube#video', 'videoId': 'TzDhdvVg9_c'},
   'snippet': {'publishedAt': '2017-05-09T20:28:46Z',
    'channelId': 'UC3cRUKVHL5tk44KzyXbV7Cg',
    'title': 'Calculus at a Fifth Grade Level',
    'description': 'The foreign concepts of calculus often make it hard to jump right into learning it. If you ever wanted to dive into the world of ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/TzDhdvVg9_c/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/TzDhdvVg9_c/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/TzDhdvVg9_c/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Lukey B. The Physics G',
    'liveBroadcastContent': 'none',
    'publishTime': '2017-05-09T20:28:46Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'h1aS5AlNhleqHLkeu8UhhGau9Ws',
   'id': {'kind': 'youtube#video', 'videoId': 'rBVi_9qAKTU'},
   'snippet': {'publishedAt': '2018-02-19T17:45:32Z',
    'channelId': 'UC0cd_-e49hZpWLH3UIwoWRA',
    'title': 'Introduction to Calculus: The Greeks, Newton, and Leibniz',
    'description': "You've been dreading this for a long time, but there's no getting around it! Once we wrap up algebra and trigonometry, it's time to ...",
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/rBVi_9qAKTU/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/rBVi_9qAKTU/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/rBVi_9qAKTU/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Professor Dave Explains',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-02-19T17:45:32Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'wdXZzKHaLPaUO-Yebbm0XXnQk6w',
   'id': {'kind': 'youtube#video', 'videoId': 'GiCojsAWRj0'},
   'snippet': {'publishedAt': '2021-01-09T16:52:52Z',
    'channelId': 'UCEWpbFLzoYGPfuWUMFPSaoA',
    'title': 'Calculus 1 Review -  Basic Introduction',
    'description': 'This back to school calculus 1 review video tutorial provides a basic introduction into a few core concepts taught in a typical AP ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/GiCojsAWRj0/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/GiCojsAWRj0/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/GiCojsAWRj0/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'The Organic Chemistry Tutor',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-01-09T16:52:52Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'QLfjkv8KHN_aFU6P5tMId0TT4pU',
   'id': {'kind': 'youtube#video', 'videoId': '5yfh5cf4-0w'},
   'snippet': {'publishedAt': '2018-07-09T03:04:08Z',
    'channelId': 'UCEWpbFLzoYGPfuWUMFPSaoA',
    'title': 'Calculus 1 - Derivatives',
    'description': 'This calculus 1 video tutorial provides a basic introduction into derivatives. Here is a list of topics: 1. The Power Rule For ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/5yfh5cf4-0w/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/5yfh5cf4-0w/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/5yfh5cf4-0w/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'The Organic Chemistry Tutor',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-07-09T03:04:08Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'L4T_8OiqhvXBTeTywEzsiVYJGzE',
   'id': {'kind': 'youtube#video', 'videoId': 'IMj5dgGWxSM'},
   'snippet': {'publishedAt': '2018-10-29T04:00:00Z',
    'channelId': 'UC5_6ZD6s8klmMu9TXEB_1IA',
    'title': 'History of Calculus - Animated',
    'description': 'Everything you need to know about calculus... in 7 minutes. Remember to subscribe and hit that bell. Follow me on Quora: ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/IMj5dgGWxSM/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/IMj5dgGWxSM/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/IMj5dgGWxSM/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'CodeEmporium',
    'liveBroadcastContent': 'none',
    'publishTime': '2018-10-29T04:00:00Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'q2krSDZcVkAlue7suERMi4x8_4I',
   'id': {'kind': 'youtube#video', 'videoId': 'tt2DGYOi3hc'},
   'snippet': {'publishedAt': '2015-06-26T23:00:01Z',
    'channelId': 'UCq0EGvLTyy-LLT1oUSO_0FQ',
    'title': 'Introduction to Calculus (1 of 2: Seeing the big picture)',
    'description': 'Main site: http://www.misterwootube.com Second channel (for teachers): http://www.youtube.com/misterwootube2 Connect with ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/tt2DGYOi3hc/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/tt2DGYOi3hc/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/tt2DGYOi3hc/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'Eddie Woo',
    'liveBroadcastContent': 'none',
    'publishTime': '2015-06-26T23:00:01Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'rqfgQbOST8tdjoZjT--zWictUa8',
   'id': {'kind': 'youtube#video', 'videoId': '7F_FsIraPyA'},
   'snippet': {'publishedAt': '2021-04-13T13:00:02Z',
    'channelId': 'UCQu86XKH-sG9k6pk8_F02Vw',
    'title': 'Calculus students be like!',
    'description': 'Just making sure” 🛍 Shop math t-shirt & hoodies: https://teespring.com/stores/blackpenredpen 💪 Become a channel member (only ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/7F_FsIraPyA/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/7F_FsIraPyA/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/7F_FsIraPyA/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'just fast',
    'liveBroadcastContent': 'none',
    'publishTime': '2021-04-13T13:00:02Z'}},
  {'kind': 'youtube#searchResult',
   'etag': '5hWCOR-mGBtlVF-xaU8HnKjg2vk',
   'id': {'kind': 'youtube#video', 'videoId': 'Y8OZqUUMAr8'},
   'snippet': {'publishedAt': '2019-11-15T13:00:08Z',
    'channelId': 'UCr7lmzIk63PZnBw3bezl-Mg',
    'title': 'What is the Hardest Calculus Course?',
    'description': 'What is the Hardest Calculus Course? Ok, so which is it? Is Calculus 1, 2, or 3 the hardest one? In this video I give specific ...',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/Y8OZqUUMAr8/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/Y8OZqUUMAr8/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/Y8OZqUUMAr8/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'The Math Sorcerer',
    'liveBroadcastContent': 'none',
    'publishTime': '2019-11-15T13:00:08Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'm7A7TKcdCYFWKjIDSjA9At0ox6g',
   'id': {'kind': 'youtube#video', 'videoId': '_kLWcuJzYh8'},
   'snippet': {'publishedAt': '2015-08-19T19:22:25Z',
    'channelId': 'UCFe6jenM1Bc54qtBsIJGRZQ',
    'title': 'Implicit Differentiation for Calculus - More Examples,  #1',
    'description': 'Thanks to all of you who support me on Patreon. You da real mvps! $1 per month helps!! :) https://www.patreon.com/patrickjmt !',
    'thumbnails': {'default': {'url': 'https://i.ytimg.com/vi/_kLWcuJzYh8/default.jpg',
      'width': 120,
      'height': 90},
     'medium': {'url': 'https://i.ytimg.com/vi/_kLWcuJzYh8/mqdefault.jpg',
      'width': 320,
      'height': 180},
     'high': {'url': 'https://i.ytimg.com/vi/_kLWcuJzYh8/hqdefault.jpg',
      'width': 480,
      'height': 360}},
    'channelTitle': 'patrickJMT',
    'liveBroadcastContent': 'none',
    'publishTime': '2015-08-19T19:22:25Z'}},
  {'kind': 'youtube#searchResult',
   'etag': 'egyHayh3e06Eggxl3ZrbLAZvJAw',
   'id': {'kind': 'youtube#video', 'videoId': 'NSfYKaJSawI'},
   'snippet': {'publishedAt': '2021-10-25T16:10:59Z',
    'channelId': 'UCglNXzBo6bmKc9otKf-OuGQ',

In [19]:
title=[]
videoid=[]
videocontent=[]
videochannel=[]
channelid=[]
videopostdate=[]
channeltitle=[]
rep_len=len(calc_results['items'])
for i in range(rep_len):
    if calc_results['items'][i]['id']['kind']=='youtube#video':
        channeltitle.append(calc_results['items'][i]['snippet']['channelTitle'])
        title.append(calc_results['items'][i]['snippet']['title'])
        videoid.append(calc_results['items'][i]['id']['videoId'])
        videochannel.append(calc_results['items'][i]['snippet']['channelTitle'])
        channelid.append(calc_results['items'][i]['snippet']['channelId'])
        videocontent.append(calc_results['items'][i]['snippet']['description'])
        videopostdate.append(calc_results['items'][i]['snippet']['publishedAt'])

In [20]:
likes,views,favs,comments=[],[],[],[]
for idt in videoid:
    a=Ytube.videos().list(part="statistics",id=idt).execute()
    likes.append(a['items'][0]['statistics']['likeCount'])
    views.append(a['items'][0]['statistics']['viewCount'])
    comments.append(a['items'][0]['statistics']['commentCount'])
    favs.append(a['items'][0]['statistics']['favoriteCount'])

In [21]:
title

['Understand Calculus in 35 Minutes',
 'Calculus 1 - Full College Course',
 'The essence of calculus',
 'Understand Calculus in 10 Minutes',
 'Calculus - Introduction to Calculus',
 'Calculus 1 Lecture 1.1:  An Introduction to Limits',
 'How to Make it Through Calculus (Neil deGrasse Tyson)',
 'What is Calculus?  (Mathematics)',
 'Your First Basic CALCULUS Problem Let’s Do It Together….',
 'Calculus 1 - Introduction to Limits',
 'Calculus at a Fifth Grade Level',
 'Introduction to Calculus: The Greeks, Newton, and Leibniz',
 'Calculus 1 Review -  Basic Introduction',
 'Calculus 1 - Derivatives',
 'History of Calculus - Animated',
 'Introduction to Calculus (1 of 2: Seeing the big picture)',
 'Calculus students be like!',
 'What is the Hardest Calculus Course?',
 'Implicit Differentiation for Calculus - More Examples,  #1',
 'How I would explain Calculus to a 6th grader',
 'Calculus | Differentiation | Basic of Limit | অন্তরীকরণ এর বেসিক|(Barun Kanti Ghosh | Athena | HSC )',
 'Why People FAIL Calculus (Fix These 3 Things to Pass)',
 '2Gether: U + Me = Us (Calculus)']

In [22]:

Calc_data=pd.DataFrame({'Views': views, 'Likes':likes, 'Number of comments': comments, 'Titles': title, 'Channel Titles': channeltitle, 'Channel ID':channelid})

In [23]:
Calc_data

,Views,Likes,Number of comments,Titles,Channel Titles,Channel ID
0,1216536,29684,1172,Understand Calculus in 35 Minutes,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
1,3208201,123282,4065,Calculus 1 - Full College Course,freeCodeCamp.org,UC8butISFwT-Wl7EV0hUK0BQ
2,6070973,171222,5684,The essence of calculus,3Blue1Brown,UCYO_jab_esuFRV4b17AJtAw
3,5600790,85264,7993,Understand Calculus in 10 Minutes,TabletClass Math,UCglNXzBo6bmKc9otKf-OuGQ
4,766590,12969,730,Calculus - Introduction to Calculus,MySecretMathTutor,UCcBOg_7QmpJFlIVMYDyUhaw
5,2795097,33773,2549,Calculus 1 Lecture 1.1: An Introduction to Li...,Professor Leonard,UCoHhuummRZaIVX7bD4t2czg
6,584797,27370,1382,How to Make it Through Calculus (Neil deGrasse...,Jonathan Arrington,UC6A_Wd8sUo5hRhn14Oxa7-A
7,1083866,22412,1019,What is Calculus? (Mathematics),Socratica,UCW6TXMZ5Pq6yL6_k5NZ2e0Q
8,168706,3794,268,Your First Basic CALCULUS Problem Let’s Do It ...,TabletClass Math,UCglNXzBo6bmKc9otKf-OuGQ
9,1143640,21653,541,Calculus 1 - Introduction to Limits,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
10,5087229,156737,10499,Calculus at a Fifth Grade Level,Lukey B. The Physics G,UC3cRUKVHL5tk44KzyXbV7Cg
11,891948,21461,897,"Introduction to Calculus: The Greeks, Newton, ...",Professor Dave Explains,UC0cd_-e49hZpWLH3UIwoWRA
12,315259,4746,140,Calculus 1 Review - Basic Introduction,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
13,895805,17262,455,Calculus 1 - Derivatives,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
14,54137,1392,123,History of Calculus - Animated,CodeEmporium,UC5_6ZD6s8klmMu9TXEB_1IA
15,2018581,36096,1436,Introduction to Calculus (1 of 2: Seeing the b...,Eddie Woo,UCq0EGvLTyy-LLT1oUSO_0FQ
16,1088135,35203,1288,Calculus students be like!,just fast,UCQu86XKH-sG9k6pk8_F02Vw
17,67060,1754,582,What is the Hardest Calculus Course?,The Math Sorcerer,UCr7lmzIk63PZnBw3bezl-Mg
18,361894,2859,82,Implicit Differentiation for Calculus - More E...,patrickJMT,UCFe6jenM1Bc54qtBsIJGRZQ
19,975875,16780,1674,How I would explain Calculus to a 6th grader,TabletClass Math,UCglNXzBo6bmKc9otKf-OuGQ
20,261936,9716,839,Calculus | Differentiation | Basic of Limit | ...,Athena Science Academy,UCWdathMvK6gjc_Lsdv60qrA
21,193918,6314,624,Why People FAIL Calculus (Fix These 3 Things t...,BriTheMathGuy,UChVUSXFzV8QCOKNWGfE56YQ
22,796091,5026,510,2Gether: U + Me = Us (Calculus),lovecupboard,UCST3EnnY8YXKmuiC_addiaQ

Found the most popular calculus videos

In [24]:
Calc_data = Calc_data.astype({'Views':int, 'Likes': int, 'Number of comments': int})
Calc_data

,Views,Likes,Number of comments,Titles,Channel Titles,Channel ID
0,1216536,29684,1172,Understand Calculus in 35 Minutes,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
1,3208201,123282,4065,Calculus 1 - Full College Course,freeCodeCamp.org,UC8butISFwT-Wl7EV0hUK0BQ
2,6070973,171222,5684,The essence of calculus,3Blue1Brown,UCYO_jab_esuFRV4b17AJtAw
3,5600790,85264,7993,Understand Calculus in 10 Minutes,TabletClass Math,UCglNXzBo6bmKc9otKf-OuGQ
4,766590,12969,730,Calculus - Introduction to Calculus,MySecretMathTutor,UCcBOg_7QmpJFlIVMYDyUhaw
5,2795097,33773,2549,Calculus 1 Lecture 1.1: An Introduction to Li...,Professor Leonard,UCoHhuummRZaIVX7bD4t2czg
6,584797,27370,1382,How to Make it Through Calculus (Neil deGrasse...,Jonathan Arrington,UC6A_Wd8sUo5hRhn14Oxa7-A
7,1083866,22412,1019,What is Calculus? (Mathematics),Socratica,UCW6TXMZ5Pq6yL6_k5NZ2e0Q
8,168706,3794,268,Your First Basic CALCULUS Problem Let’s Do It ...,TabletClass Math,UCglNXzBo6bmKc9otKf-OuGQ
9,1143640,21653,541,Calculus 1 - Introduction to Limits,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
10,5087229,156737,10499,Calculus at a Fifth Grade Level,Lukey B. The Physics G,UC3cRUKVHL5tk44KzyXbV7Cg
11,891948,21461,897,"Introduction to Calculus: The Greeks, Newton, ...",Professor Dave Explains,UC0cd_-e49hZpWLH3UIwoWRA
12,315259,4746,140,Calculus 1 Review - Basic Introduction,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
13,895805,17262,455,Calculus 1 - Derivatives,The Organic Chemistry Tutor,UCEWpbFLzoYGPfuWUMFPSaoA
14,54137,1392,123,History of Calculus - Animated,CodeEmporium,UC5_6ZD6s8klmMu9TXEB_1IA
15,2018581,36096,1436,Introduction to Calculus (1 of 2: Seeing the b...,Eddie Woo,UCq0EGvLTyy-LLT1oUSO_0FQ
16,1088135,35203,1288,Calculus students be like!,just fast,UCQu86XKH-sG9k6pk8_F02Vw
17,67060,1754,582,What is the Hardest Calculus Course?,The Math Sorcerer,UCr7lmzIk63PZnBw3bezl-Mg
18,361894,2859,82,Implicit Differentiation for Calculus - More E...,patrickJMT,UCFe6jenM1Bc54qtBsIJGRZQ
19,975875,16780,1674,How I would explain Calculus to a 6th grader,TabletClass Math,UCglNXzBo6bmKc9otKf-OuGQ
20,261936,9716,839,Calculus | Differentiation | Basic of Limit | ...,Athena Science Academy,UCWdathMvK6gjc_Lsdv60qrA
21,193918,6314,624,Why People FAIL Calculus (Fix These 3 Things t...,BriTheMathGuy,UChVUSXFzV8QCOKNWGfE56YQ
22,796091,5026,510,2Gether: U + Me = Us (Calculus),lovecupboard,UCST3EnnY8YXKmuiC_addiaQ

In [25]:
Sorted_views = Calc_data['Views'].sort_values(ascending = False)

In [26]:

most_pop_calc_vids = pd.DataFrame({'Views': Sorted_views, 
                                   'Titles':title})

In [27]:
most_pop_calc_vids

      Views                                             Titles
2   6070973                  Understand Calculus in 35 Minutes
3   5600790                   Calculus 1 - Full College Course
10  5087229                            The essence of calculus
1   3208201                  Understand Calculus in 10 Minutes
5   2795097                Calculus - Introduction to Calculus
15  2018581  Calculus 1 Lecture 1.1:  An Introduction to Li...
0   1216536  How to Make it Through Calculus (Neil deGrasse...
9   1143640                   What is Calculus?  (Mathematics)
16  1088135  Your First Basic CALCULUS Problem Let’s Do It ...
7   1083866                Calculus 1 - Introduction to Limits
19   975875                    Calculus at a Fifth Grade Level
13   895805  Introduction to Calculus: The Greeks, Newton, ...
11   891948            Calculus 1 Review -  Basic Introduction
22   796091                           Calculus 1 - Derivatives
4    766590                     History of Calculus - Animated
6    584797  Introduction to Calculus (1 of 2: Seeing the b...
18   361894                         Calculus students be like!
12   315259               What is the Hardest Calculus Course?
20   261936  Implicit Differentiation for Calculus - More E...
21   193918       How I would explain Calculus to a 6th grader
8    168706  Calculus | Differentiation | Basic of Limit | ...
17    67060  Why People FAIL Calculus (Fix These 3 Things t...
14    54137                    2Gether: U + Me = Us (Calculus)

Find the Youtuber with the most popular calculus videos.

In [54]:
 most_pop_Utuber = pd.DataFrame({'Views': Sorted_views, 
                                 'Titles':title,
                                  'Channel Titles': channeltitle})

In [55]:
most_pop_Utuber.iloc[0] # This will find the amount of views the most popular youtuber has and thte title of the video.

Views                                       6070973
Titles            Understand Calculus in 35 Minutes
Channel Titles          The Organic Chemistry Tutor
Name: 2, dtype: object

Youtubers with the most amount of Calculus Videos

In [30]:
most_utuber = Calc_data['Channel Titles']

In [31]:
most_utuber.values

array(['The Organic Chemistry Tutor', 'freeCodeCamp.org', '3Blue1Brown',
       'TabletClass Math', 'MySecretMathTutor', 'Professor Leonard',
       'Jonathan Arrington', 'Socratica', 'TabletClass Math',
       'The Organic Chemistry Tutor', 'Lukey B. The Physics G',
       'Professor Dave Explains', 'The Organic Chemistry Tutor',
       'The Organic Chemistry Tutor', 'CodeEmporium', 'Eddie Woo',
       'just fast', 'The Math Sorcerer', 'patrickJMT', 'TabletClass Math',
       'Athena Science Academy', 'BriTheMathGuy', 'lovecupboard'],
      dtype=object)

In [34]:
most_appeared = 'The Organic Chemistry Tutor', 'freeCodeCamp.org', '3Blue1Brown','TabletClass Math', 'Professor Leonard', 'MySecretMathTutor','The Organic Chemistry Tutor', 'Socratica', 'Jonathan Arrington','Lukey B. The Physics G', 'The Organic Chemistry Tutor','Professor Dave Explains', 'Eddie Woo','The Organic Chemistry Tutor', 'CodeEmporium', 'just fast','The Organic Chemistry Tutor', 'TabletClass Math','The Math Sorcerer', 'TabletClass Math', 'patrickJMT','Athena Science Academy', 'TabletClass Math'
# most_appeared  is the raw list, where the youtubers are shown multiple times.
ma = set(most_appeared) # unique keys 
ma

{'3Blue1Brown',
 'Athena Science Academy',
 'CodeEmporium',
 'Eddie Woo',
 'Jonathan Arrington',
 'Lukey B. The Physics G',
 'MySecretMathTutor',
 'Professor Dave Explains',
 'Professor Leonard',
 'Socratica',
 'TabletClass Math',
 'The Math Sorcerer',
 'The Organic Chemistry Tutor',
 'freeCodeCamp.org',
 'just fast',
 'patrickJMT'}

In [35]:
dict1 = {'3Blue1Brown': str(most_appeared.count('3Blue1Brown')),
 'Athena Science Academy': str(most_appeared.count('Athena Science Academy')),
 'CodeEmporium': str(most_appeared.count('CodeEmporium')),
 'Eddie Woo': str(most_appeared.count('Eddie Woo')),
 'Jonathan Arrington': str(most_appeared.count('Jonathan Arrington')),
 'Lukey B. The Physics G': str(most_appeared.count('Lukey B. The Physics G')) ,
 'MySecretMathTutor': str(most_appeared.count('MySecretMathTutor')) ,
 'Professor Dave Explains': str(most_appeared.count('Professor Dave Explains')) ,
 'Professor Leonard': str(most_appeared.count('Professor Leonard')),
 'Socratica': str(most_appeared.count('Socratica')),
 'TabletClass Math': str(most_appeared.count('TabletClass Math')) ,
 'The Math Sorcerer': str(most_appeared.count('The Math Sorcerer')),
 'The Organic Chemistry Tutor': str(most_appeared.count('The Organic Chemistry Tutor')) ,
 'freeCodeCamp.org':str(most_appeared.count('freeCodeCamp.org')) ,
 'just fast':str(most_appeared.count('just fast')) ,
 'patrickJMT': str(most_appeared.count('patrickJMT'))}

# Make a dictionary and most_appeared is the raw list

In [38]:
max_value = max(dict1, key=dict1.get) # Find the youtuber with the most calculus videos 
print(max_value, 'has the most with ', dict1[max_value], 'calculus videos.')

The Organic Chemistry Tutor has the most with  5 calculus videos

In [42]:
most_data = pd.DataFrame({'Youtubers with most calculus videos' : [max_value],
                         '# of Videos': [dict1[max_value]]})

In [43]:
most_data # Put it in a dataframe

  Youtubers with most calculus videos # of Videos
0         The Organic Chemistry Tutor           5